services:
  - type: web
    name: job-scraper
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod +x build.sh
      ./build.sh
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10